/**
 * The narrative pages (bean `jut3`): Liquid resolved as measured, links that
 * resolve, and every gap reported rather than dropped.
 *
 * The last block reads the COMMITTED output, because the defect this guards
 * against — a link right as a string and wrong as a URL — is invisible in the
 * generator's own code and only shows in what it wrote (issue #824).
 */
import { describe, expect, it } from "bun:test";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { evalOutput, narrativeTitle, renderNarrative, rewriteHref, type NarrativeContext } from "../narrative-pages.ts";

const BASE = "https://example.org/ig";

function ctx(sources: Record<string, string>): NarrativeContext {
  return {
    sources: new Map(Object.entries(sources)),
    publishedBase: BASE,
    packageId: "smart.who.int.trust",
    artifactHref: (n) => (n === "ActorDefinition-Holder" ? "../artifact/ActorDefinition-Holder.html" : undefined),
    artifactsOfType: (t) => (t === "ActorDefinition" ? [{ label: "Holder", href: "../artifact/ActorDefinition-Holder.html" }] : []),
  };
}

describe("evalOutput — the one data path the pages read", () => {
  it("evaluates the filter chain feedback.md uses", () => {
    expect(evalOutput("site.data.fhir.packageId | split: '.' | last | prepend: 'https://x/'", "smart.who.int.trust")).toBe("https://x/trust");
  });
  it("refuses anything it does not model, rather than guessing", () => {
    expect(evalOutput("PARTICIPANT_CODE", "p")).toBeUndefined();
    expect(evalOutput("site.data.fhir.packageId | upcase", "p")).toBeUndefined();
  });
});

describe("rewriteHref", () => {
  const c = ctx({ "concepts.md": "" });
  it("keeps a link to a snapshotted page local, fragment and all", () => {
    expect(rewriteHref("concepts.html#x", c)).toBe("concepts.html#x");
    expect(rewriteHref("./concepts.html", c)).toBe("concepts.html");
  });
  it("sends an artefact link to this site's artefact page", () => {
    expect(rewriteHref("ActorDefinition-Holder.html", c)).toBe("../artifact/ActorDefinition-Holder.html");
  });
  it("sends everything else to the published IG", () => {
    expect(rewriteHref("figure.png", c)).toBe(`${BASE}/figure.png`);
    expect(rewriteHref("artifacts.html", c)).toBe(`${BASE}/artifacts.html`);
  });
  it("leaves absolute, anchor and already site-relative links alone", () => {
    for (const h of ["https://a/b", "mailto:x@y", "#top", "../artifact/X.html"]) expect(rewriteHref(h, c)).toBe(h);
  });
});

describe("renderNarrative", () => {
  it("transcludes an included page and reports a Publisher fragment instead of dropping it", () => {
    const r = renderNarrative("a.md", ctx({ "a.md": "A {% include b.md %} {% include dependency-table.xhtml %}", "b.md": "---\nx: 1\n---\nB" }));
    expect(r.body).toContain("A B");
    expect(r.body).toContain("generated by the IG Publisher");
    expect(r.gaps).toEqual(["a.md: include dependency-table.xhtml (Publisher output, not source)"]);
  });
  it("renders img.html as the markup it emits, with the image on the published IG", () => {
    const r = renderNarrative("a.md", ctx({ "a.md": `{% include img.html img="f.png" caption="Fig" width="50%" %}` }));
    expect(r.body).toContain(`<img src="${BASE}/f.png" alt="Fig" style="width:50%"/>`);
  });
  it("turns the canonicals loop into the index's artefacts of that type", () => {
    const src = "{% assign cs = site.data.canonicals | where: 'type' , 'ActorDefinition' %}\n{% for c in cs %}\n{% include x.liquid %}\n{% endfor %}";
    const r = renderNarrative("a.md", ctx({ "a.md": src }));
    expect(r.body).toContain("- [Holder](../artifact/ActorDefinition-Holder.html)");
    expect(r.gaps).toEqual([]);
  });
  it("keeps an unless body (the Publisher excludes nothing by default) and drops the tags", () => {
    const r = renderNarrative("a.md", ctx({ "a.md": "{% assign e = site.data.info.excludexml %}{% unless e == 'y' %}XML{% endunless %}" }));
    expect(r.body).toContain("XML");
    expect(r.body).not.toContain("unless");
  });
  it("leaves an unknown output as text, reports it, and raw-wraps it so Jekyll cannot eat it", () => {
    const r = renderNarrative("a.md", ctx({ "a.md": "code {{PARTICIPANT_CODE}} here" }));
    expect(r.body).toContain("{{PARTICIPANT_CODE}}");
    expect(r.body.startsWith("{% raw %}")).toBe(true);
    expect(r.gaps).toEqual(["a.md: {{ PARTICIPANT_CODE }} left as written"]);
  });
  it("stops a self-including page instead of recursing forever", () => {
    const r = renderNarrative("a.md", ctx({ "a.md": "x{% include a.md %}" }));
    expect(r.gaps.some((g) => g.includes("deeper than"))).toBe(true);
  });
});

describe("narrativeTitle", () => {
  it("prefers the tree, then the first heading, then the filename", () => {
    expect(narrativeTitle("a.md", "Tree", "# H")).toBe("Tree");
    expect(narrativeTitle("a.md", undefined, "---\nx: 1\n---\n### Heading ###\n")).toBe("Heading");
    expect(narrativeTitle("a.md", undefined, "no heading")).toBe("a");
  });
});

// ── The committed output ───────────────────────────────────────────────
const INSTANCE = resolve(dirname(import.meta.path), "..", "..");
const DOCS = join(INSTANCE, "docs");
const PAGES = join(DOCS, "pages");
const MANIFEST = join(INSTANCE, "ig-pages", "pages.json");

describe.skipIf(!existsSync(MANIFEST))("the committed narrative pages", () => {
  const manifest = JSON.parse(readFileSync(MANIFEST, "utf8")) as { pages: Array<{ file: string }> };
  const files = readdirSync(PAGES).filter((f) => f.endsWith(".md"));

  it("exist one per snapshotted source — and there are some", () => {
    expect(manifest.pages.length).toBeGreaterThan(0);
    expect(files.sort()).toEqual(manifest.pages.map((p) => p.file).sort());
  });

  it("link only to pages that exist, once built", () => {
    const broken: string[] = [];
    for (const f of files) {
      const text = readFileSync(join(PAGES, f), "utf8");
      for (const m of text.matchAll(/(?:\]\(|href=")([^)"\s#]+\.html)(?:#[^)"]*)?[)"]/g)) {
        const href = m[1]!;
        if (/^[a-z]+:/i.test(href)) continue;
        // Jekyll writes X.md as X.html: resolve the href back to its SOURCE.
        const target = join(PAGES, href.replace(/\.html$/, ".md"));
        if (!existsSync(target)) broken.push(`${f} → ${href}`);
      }
    }
    expect(broken).toEqual([]);
  });

  it("never point at the published IG through a relative path", () => {
    const bad = files.filter((f) => /https?:\/\/[^)"\s]*\/\.\.\//.test(readFileSync(join(PAGES, f), "utf8")));
    expect(bad).toEqual([]);
  });

  const ruby = spawnSync("ruby", ["-e", 'require "liquid"'], { encoding: "utf-8" }).status === 0;
  it.skipIf(!ruby)("parse as Liquid in strict mode, every one", () => {
    const script =
      'require "liquid"; bad = []; ARGV.each { |f| begin; Liquid::Template.parse(File.read(f, encoding: "UTF-8"), error_mode: :strict); rescue => e; bad << "#{f}: #{e.message}"; end }; puts bad';
    const r = spawnSync("ruby", ["-e", script, ...files.map((f) => join(PAGES, f))], { encoding: "utf-8" });
    expect(r.stdout.trim()).toBe("");
  });
});
